repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.8
  hooks:
    # Run the linter (must come before any formatter, black/ruff when --fix).
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: local
  hooks:
    - id: copyright
      name: Check copyright header
      files: '\.py$'
      language: system
      entry: ./copyright_check