name: Pull Request Tests

on: [pull_request]


jobs:
  lower-bound-packages:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        pipconf: ["", "minver"]

    steps:
      # SETUP
      ############################
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Ensure branch is checked out, not detached state (so we can push a commit later)
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Install dependencies
        id: install-dependencies
        run: |
          pip install .[tests,visualisation,dev,${{ matrix.pipconf }}]

      - name: Set up SSH for localhost
        run: |
          ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          ssh-keyscan -H $(hostname) >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/authorized_keys

      - name: Run pytest + coverage report gen
        run: |
          if [ "${{ matrix.pipconf }}" == "minver" ]; then
            pytest --cov=dagrunner --cov-report=term --cov-report=html | tee coverage_output.txt; test ${PIPESTATUS[0]} -eq 0
          else
            pytest .

      # PRE-COMMIT
      ############################
      - name: Python interpreter version sha (PYSHA)
        if: ${{ matrix.pipconf == 'minver' }}
        run: echo "PYSHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache pre-commit
        if: ${{ matrix.pipconf == 'minver' }}
        uses: actions/cache@v3
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PYSHA }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit install
        if: ${{ matrix.pipconf == 'minver' }}
        run: |
          pre-commit install

      - name: pre-commit run
        if: ${{ matrix.pipconf == 'minver' }}
        run: |
          pre-commit run --all-files

      # Compare coverage reports
      ############################
      - name: Download main branch coverage report
        if: ${{ matrix.pipconf == 'minver' }}
        uses: actions/download-artifact@v4
        with:
          name: main-coverage-report
          path: ref

      - name: Compare coverage
        if: ${{ matrix.pipconf == 'minver' }}
        id: comp-coverage
        run: |
            pr_coverage_total=$(grep TOTAL coverage_output.txt | awk '{print $NF}' | awk '{print substr($0, 1, length($0)-1)}')
            echo "pr_coverage_total=$pr_coverage_total" | tee -a $GITHUB_OUTPUT
            ref_coverage_total=$(grep TOTAL ref/coverage_output.txt | awk '{print $NF}' | awk '{print substr($0, 1, length($0)-1)}')
            echo "ref_coverage_total=$ref_coverage_total" | tee -a $GITHUB_OUTPUT
            if (( (( ref_coverage_total - pr_coverage_total )) > 1 )); then
                echo "coverage_decreased=true" | tee -a $GITHUB_OUTPUT
            else
                echo "coverage_decreased=false" | tee -a $GITHUB_OUTPUT
            fi

      - name: Comment coverage report
        if: ${{ matrix.pipconf == 'minver' && steps.comp-coverage.outputs.coverage_decreased == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            let comment = String();
            comment = "The test coverage has decreased from ${{ steps.comp-coverage.outputs.ref_coverage_total }}% to ${{ steps.comp-coverage.outputs.pr_coverage_total }}% (commit SHA: ${{ github.event.pull_request.head.sha }})."
            comment += "\nPlease review test coverage.  Report uploaded as artifact.";
            console.log(comment)
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Upload coverage report
        if: ${{ matrix.pipconf == 'minver' && steps.comp-coverage.outputs.coverage_decreased == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-pr
          path: |
            coverage_output.txt
            htmlcov/