name: Pull Request Tests

on: [pull_request]


jobs:
  pre-commit:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      # SETUP
      ############################
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Add checkout directory to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Install dependencies
        id: install-dependencies
        run: |
          pip install .[tests,visualisation,dev]
          pip uninstall dagrunner -y

      # PRE-COMMIT
      ############################
      - name: Python interpreter version sha (PYSHA)
        run: echo "PYSHA=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache pre-commit
        uses: actions/cache@v3
        id: pre-commit-cache
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PYSHA }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit install
        run: |
          pre-commit install

      - name: pre-commit run
        run: |
          pre-commit run --all-files


  lower-bound-packages:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      # SETUP
      ############################
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Add checkout directory to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Install dependencies
        id: install-dependencies
        run: |
          pip install .[tests,visualisation,minver]
          pip uninstall dagrunner -y

      - name: Set up SSH for localhost
        run: |
          ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          ssh-keyscan -H $(hostname) >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/authorized_keys

      # TESTS
      ############################
      - name: Run pytest
        run: pytest .

      # DOCUMENTATION
      ############################
      - name: Build documentation
        run: |
          ./docs/gen_docs dagrunner ./docs

      - name: Check if documentation has changed
        id: check-docs
        run: |
          echo "changed=$(git diff --quiet --exit-code || echo true)" | tee -a $GITHUB_OUTPUT


  unpinned-packages-test-coverage:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      # SETUP
      ############################
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: 'pip'

      - name: Add checkout directory to PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV

      - name: Install dependencies
        id: install-dependencies
        run: |
          pip install .[tests,visualisation,dev]
          pip uninstall dagrunner -y

      - name: Set up SSH for localhost
        run: |
          ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
          ssh-keyscan -H $(hostname) >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/authorized_keys

      # TESTS (inc. test coverage)
      ############################
      - name: Run pytest + coverage report gen
        run: pytest --cov=dagrunner --cov-report=term --cov-report=html | tee coverage_output.txt; test ${PIPESTATUS[0]} -eq 0

      # TESTS ('main' branch)
      ############################
      - name: Cache ref branch coverage report
        id: cache-ref-coverage
        uses: actions/cache@v4
        with:
          path: ref/coverage_output.txt
          key: ref-${{ github.event.pull_request.base.sha }}

      - name: Checkout ref branch
        if: steps.cache-ref-coverage.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          path: ref
          ref: ${{ github.base_ref }}

      - name: Run tests with coverage for ref branch
        if: steps.cache-ref-coverage.outputs.cache-hit != 'true'
        run: |
          cd ref
          pytest --maxfail=0 --continue-on-collection-errors --cov=dagrunner --cov-report=term --cov-report=html | tee coverage_output.txt || true

      # TESTS (compare coverage)
      ############################
      - name: Compare coverage
        id: comp-coverage
        run: |
          set -e
          # ----- USER SETTINGS -------------------------------------------------
          CHECK_MISS_TOL=1      # 1 = evaluate the miss‑count difference, 0 = ignore it
          CHECK_PERC_TOL=0      # 1 = evaluate the percentage difference, 0 = ignore it

          # Tolerances
          miss_tol=0          # miss integer tolerance
          perc_tol=0.0        # percentage float tolerance
          # --------------------------------------------------------------------

          read pr_tot_stmts pr_tot_miss <<< $(awk '/^[[:space:]]*TOTAL/ {print $2, $3}' coverage_output.txt)
          pr_perc_total=$(echo "scale=4; ($pr_tot_stmts-$pr_tot_miss)/$pr_tot_stmts"'*100' | bc)
          echo "pr_perc_total=$pr_perc_total" | tee -a $GITHUB_OUTPUT
          echo "pr_tot_stmts=$pr_tot_stmts" | tee -a $GITHUB_OUTPUT
          echo "pr_tot_miss=$pr_tot_miss" | tee -a $GITHUB_OUTPUT

          if [ ! -f ref/coverage_output.txt ]; then
              echo "Warning: ref/coverage_output.txt does not exist, reporting coverage."
              echo "coverage_decreased=true" | tee -a $GITHUB_OUTPUT
              echo "ref_perc_total=--" | tee -a $GITHUB_OUTPUT
              echo "ref_tot_stmts=--" | tee -a $GITHUB_OUTPUT
              echo "ref_tot_miss=--" | tee -a $GITHUB_OUTPUT
              exit 0
          else
              read ref_tot_stmts ref_tot_miss <<< $(awk '/^[[:space:]]*TOTAL/ {print $2, $3}' ref/coverage_output.txt)
              ref_perc_total=$(echo "scale=4; ($ref_tot_stmts-$ref_tot_miss)/$ref_tot_stmts"'*100' | bc)
              echo "ref_perc_total=$ref_perc_total" | tee -a $GITHUB_OUTPUT
              echo "ref_tot_stmts=$ref_tot_stmts" | tee -a $GITHUB_OUTPUT
              echo "ref_tot_miss=$ref_tot_miss" | tee -a $GITHUB_OUTPUT

              trigger=0

              miss_diff=$(( ref_tot_miss_b - pr_tot_miss_a ))               # integer diff
              perc_diff=$(bc <<< "scale=4; $ref_perc_total - $pr_perc_total")       # float diff

              if (( CHECK_MISS_TOL == 1 )) && (( miss_diff > miss_tol )); then
                  trigger=1
              fi
              if (( CHECK_PERC_TOL == 1 )) && (( $(bc <<< "$perc_diff > $perc_tol") )); then
                  trigger=1
              fi
              trigger=1  # debug: force trigger
              if (( trigger == 1 )); then
                  echo "coverage_decreased=true" | tee -a $GITHUB_OUTPUT
              else
                  echo "coverage_decreased=false" | tee -a $GITHUB_OUTPUT
              fi
          fi

      - name: Upload coverage report
        if: steps.comp-coverage.outputs.coverage_decreased == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-pr
          path: |
            coverage_output.txt
            htmlcov/

      - name: Reduced coverage failure
        if: steps.comp-coverage.outputs.coverage_decreased == 'true'
        run:  |
            echo "Code coverage has decreased"
            echo "-----------------------------------------------"
            echo -e "Coverage totals\tstatements\tmissed\n\
            PR\t${{ steps.comp-coverage.outputs.pr_tot_stmts }}\t${{ steps.comp-coverage.outputs.pr_tot_miss }}\t${{ steps.comp-coverage.outputs.pr_perc_total }}%\n\
            Reference\t${{ steps.comp-coverage.outputs.ref_tot_stmts }}\t${{ steps.comp-coverage.outputs.ref_tot_miss }}\t${{ steps.comp-coverage.outputs.ref_perc_total }}%" \
            | column -t -s $'\t'
            echo "-----------------------------------------------"
            echo "Report uploaded as artifact 'coverage-report-pr'"
            exit 1